/* Generated By:JJTree&JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 1;
  /** RegularExpression Id. */
  int OR = 2;
  /** RegularExpression Id. */
  int IMPLIES = 3;
  /** RegularExpression Id. */
  int EQUIVALENT = 4;
  /** RegularExpression Id. */
  int PREDICATE = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<AND>",
    "<OR>",
    "<IMPLIES>",
    "<EQUIVALENT>",
    "<PREDICATE>",
  };

}
