/* Generated By:JavaCC: Do not edit this line. AssignmentTreeConstants.java Version 5.0 */
public interface AssignmentTreeConstants
{
  public int JJTVOID = 0;
  public int JJTAND = 1;
  public int JJTOR = 2;
  public int JJTIMPLIES = 3;
  public int JJTEQUIVALENT = 4;
  public int JJTPREDICATE = 5;


  public String[] jjtNodeName = {
    "void",
    "And",
    "Or",
    "Implies",
    "Equivalent",
    "Predicate",
  };
}
/* JavaCC - OriginalChecksum=0aebd1e2c917e38806a68deeebf211e3 (do not edit this line) */
