/* Generated By:JJTree: Do not edit this line. ASTEquivalent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEquivalent extends SimpleNode {
  public ASTEquivalent(int id) {
    super(id);
  }

  public ASTEquivalent(Assignment p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=45f3d01d74b27b16f89572643f2bf421 (do not edit this line) */
