/* Generated By:JJTree: Do not edit this line. ASTFormula.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFormula extends SimpleNode {
  public ASTFormula(int id) {
    super(id);
  }

  public ASTFormula(Assignment p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a4a893046a65aa08be19de3b49593145 (do not edit this line) */
