/* Generated By:JJTree: Do not edit this line. ASTImplies.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImplies extends SimpleNode {
  public ASTImplies(int id) {
    super(id);
  }

  public ASTImplies(Assignment p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85402c327db1d08a817c3fbed6014f9f (do not edit this line) */
