/* Generated By:JJTree: Do not edit this line. ASTPredicate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPredicate extends SimpleNode {
  public ASTPredicate(int id) {
    super(id);
  }

  public ASTPredicate(Assignment p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ffc138c4f92d9b4db3de941f94206cd7 (do not edit this line) */
