/* Generated By:JavaCC: Do not edit this line. CalcInputParserTreeConstants.java Version 5.0 */
public interface CalcInputParserTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTNUMBER = 1;


  public String[] jjtNodeName = {
    "Input",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=cc639218e3f67bb866a72bb5c6937827 (do not edit this line) */
